# Generated by Django 2.1.2 on 2018-10-24 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(blank=True, max_length=200, null=True)),
                ('adoption_date', models.DateTimeField(verbose_name='adoption date')),
                ('profile_pic', models.ImageField(upload_to='')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(blank=True, max_length=200, null=True)),
                ('common_name', models.CharField(blank=True, max_length=200, null=True)),
                ('light_requirement', models.CharField(choices=[('DIRECT', 'Direct Bright'), ('INDIRECT', 'Indirect Bright'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='INDIRECT', max_length=200)),
                ('temp_requirement', models.CharField(choices=[('MEDIUM', '60 - 80 deg F')], default='MEDIUM', max_length=200)),
                ('humidity_requirement', models.CharField(choices=[('HIGH', 'High Humidity'), ('MEDIUM', 'Medium Humidity'), ('LOW', 'Low Humidity')], default='MEDIUM', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.Species'),
        ),
    ]
