# Generated by Django 2.1.2 on 2018-10-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='adoption_date',
            field=models.DateField(verbose_name='adoption date'),
        ),
    ]
