# Generated by Django 2.1.2 on 2019-04-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_auto_20181024_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='adoption_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='adoption date'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
