# Generated by Django 2.1.2 on 2019-04-26 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='publish date'),
        ),
    ]
