# Generated by Django 2.1.2 on 2018-10-24 15:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20181024_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 24, 15, 55, 5, 54255, tzinfo=utc), verbose_name='publish date'),
        ),
    ]
