# Generated by Django 2.1.2 on 2018-10-24 16:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20181024_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 24, 16, 29, 46, 478585, tzinfo=utc), verbose_name='publish date'),
        ),
    ]
