# Generated by Django 2.1.2 on 2018-10-24 16:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_auto_20181024_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 24, 16, 32, 16, 123777, tzinfo=utc), verbose_name='publish date'),
        ),
    ]
