# Generated by Django 2.1.2 on 2019-04-25 19:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_auto_20181024_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 25, 19, 21, 39, 170974, tzinfo=utc), verbose_name='publish date'),
        ),
    ]
